# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./dbs/my.cnf:/etc/mysql/my.cnf
#      - /var/run/mysqld/:/var/run/mysqld/
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
